### ISSUE TITLE
Pls teach me how deploy in Linux Ubuntu from scratch

### ISSUE THREAD

**Issue by johnfelipe** [akshay-gupta123/Cattle-detection#1]
Hi dear can u help me 
I have new Linux Ubuntu 18 from scratch
May be a cheatsheet with all commands for test your app
Tnks

**Comment by akshay-gupta123** [comment]
Hi, follow the steps:
Most factory versions of Ubuntu 18.04 or Ubuntu 20.04 come with Python pre-installed. Check your version of Python by entering the following:
``` python ––version ```
If the revision level is lower than 3.7.x, or if Python is not installed, then download it using link [Link](https://phoenixnap.com/kb/how-to-install-python-3-ubuntu)

Now download the pip
```
sudo apt update
sudo apt install python3-pip
```
Check it using
```
pip3 --version
```
Now download the dependencies
- Numpy: ```pip install numpy```
- torch:  [Link](http://torch.ch/docs/getting-started.html)
- openCV: ```sudo apt-get install python3-opencv```

After downloading the dependencies, clone the repo and you are good to go for testing.

**Comment by johnfelipe** [comment]
I will do all steps and share u my cheatsheet for future users like me
Tnks a lot
