### ISSUE TITLE
my commands

### ISSUE THREAD

**Issue by johnfelipe** [akshay-gupta123/Cattle-detection#3]
sudo apt update
	sudo apt install python3-pip
	pip3 --version

To use pip to install PyTorch without GPU support, run

	pip3 install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

	pip install numpy

	sudo apt-get install python3-opencv
	git clone https://github.com/akshay-gupta123/Cattle-detection.git
	cd Cattle-detection
	pip install -r requirements.txt

show me this error

	root@detection-ubuntu-s-8vcpu-16gb-nyc1-01:~/Cattle-detection# pip install -r requirements.txt
	Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.5.1+cpu)
	ERROR: Could not find a version that satisfies the requirement opecv-python (from -r requirements.txt (line 2)) (from versions: none)
	ERROR: No matching distribution found for opecv-python (from -r requirements.txt (line 2))

**Comment by akshay-gupta123** [comment]
As you have already installed the requirements, now you don't have to use the ```pip install -r requirements.txt ```.
Directly use ```python detect.py --arguments```

**Comment by johnfelipe** [comment]
Pls dear tell me all commands in scratch Ubuntu 20.04 lts I'm suffering here trying test your app I need show to my students with Venezuelan catle

**Comment by johnfelipe** [comment]
python3 detect.py –arguments

	Traceback (most recent call last):
	  File "detect.py", line 2, in <module>
		import cv2
	ModuleNotFoundError: No module named 'cv2'

**Comment by akshay-gupta123** [comment]
Please check whether cv2 is installed properly or not. Can you use colab, then I will share one with you. You will not face any problem there.

**Comment by johnfelipe** [comment]
can u explain what is colab?

**Comment by akshay-gupta123** [comment]
Google Colaboratory [Link](https://colab.research.google.com/notebooks/intro.ipynb?utm_source=scs-index)
It's like jupyter  notebook by Google.

**Comment by johnfelipe** [comment]
https://colab.research.google.com/drive/1lwWmiV0GyD5MB7ZtVGQVUGsyiRpuFcqE?usp=sharing

**Comment by akshay-gupta123** [comment]
Use it [Link](https://colab.research.google.com/drive/16rjKIr7ZmyKk3kpcTpt8Xz7FDQyQ4Ny8?usp=sharing)
